version: '3.1'

services:
  drupal:
    image: drupal
    ports:
      - 8080:80
    volumes:
      - modules:/var/www/html/modules
      - profiles:/var/www/html/profiles
      - themes:/var/www/html/themes
      # this takes advantage of the feature in Docker that a new anonymous
      # volume (which is what we're creating here) will be initialized with the
      # existing content of the image at the same location
      - sites:/var/www/html/sites
    restart: always

  postgres: 
    image: postgres:9.6
    ports: 
      - 5442:5432
    environment:
      POSTGRES_PASSWORD: postgres
    restart: always

volumes:
  modules: 
  profiles: 
  themes: 
  sites: 
